#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MARC-Descriptions
version:      0.9
version_from: lib/MARC/Descriptions.pm
installdirs:  site
requires:
    Clone:                         0
    Clone::Any:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
